version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance-trader
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"  # localhost만 접근 가능
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    volumes:
      - ./logs:/app/logs  # 로그 저장 (선택사항)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
